name: Test
on: push
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-version:
          - 4.13.1
        lib-version:
          - 1.1.0
          - 2.0.0
          - 2.1.2
          - 2.2.0
          - 2.3.0
          - 3.0.0
          - 3.1.0
          - 3.2.0
          - 3.3.0
          - 3.4.0
          - 3.5.0
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}
      - run: opam install dune base64.${{ matrix.lib-version }}
      - run: eval $(opam env)
      - run: dune exec ./test.exe
